package Jiu.java;

/**
 * @author Jiuneng Zhang
 * @create 2021-12-18-2:34 pm
 */
public class TemplatesTest1 {

    public static final int NUM = 10;

    // pric -- private int with comments
    /**
     * the ID of the comtumer
     */
     private int id;

    // prsc -- private String with comments
     /**
      * the name of the comtumer
      */
      private String name;


    // psvm / main
    public static void main(String[] args) {

    }

    // the template generated by test
    public void testUpdate(){
        // the test that are modified
    }
    
}
